In [2]:
from PIL import Image
import numpy as np

In [ ]:
def createExamples():
    numberArrayExamples = open('numArEx.txt','a')
    numbersWeHave = range(1,10)
    for eachNum in numbersWeHave:
        #print eachNum
        for furtherNum in numbersWeHave:
            # you could also literally add it *.1 and have it create
            # an actual float, but, since in the end we are going
            # to use it as a string, this way will work.
            print(str(eachNum)+'.'+str(furtherNum))
            imgFilePath = 'images/numbers/'+str(eachNum)+'.'+str(furtherNum)+'.png'
            ei = Image.open(imgFilePath)
            eiar = np.array(ei)
            eiarl = str(eiar.tolist())

            print(eiarl)
            lineToWrite = str(eachNum)+'::'+eiarl+'\n'
            numberArrayExamples.write(lineToWrite)

In [ ]:
def thresholding(image_array):
    std = []
    new_array = image_array
    for row in image_array:
        for pixel in row:
            avg = reduce(lambda x, y : x+y, pixel[:3])/3
            std.append(avg)
    balance = mean(std)
    for row in new_array:
        for pixel in row:
            if reduce(lambda x, y : x+y, pixel[:3])/3 > balance:
                pixel[0] = 255
                pixel[1] = 255
                pixel[2] = 255
                pixel[3] = 255
            else:
                pixel[0] = 0
                pixel[1] = 0
                pixel[2] = 0
                pixel[3] = 255
    return new_array    

In [11]:
image = Image.open("E:/tutorialimages/images/numbers/0.1.png", mode = 'r')
im_ar = np.asarray(image)
print(im_ar)

[[[255 255 255 255]
  [255 255 255 255]
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [  0   0   0 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [  0   0   0 255]
  [255 255 255 255]]

 [[  0   0   0 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  [  0   0   0 255]]

 [[255 255 255 255]
  [  0  